const funcURL = (type:string) => `https://raw.githubusercontent.com/DanilImi/storage-gallery/main/${type}.webp`

export const dataSetImage = {
  laptop: funcURL('laptop'),
  satergo: funcURL('satergo'),
  ergonodes: funcURL('ergonodes'),
  aline: funcURL('aline'),
  samurai: funcURL('samurai'),
  emporas: funcURL('emporas'),
  gooseart: funcURL('gooseart'),
  kbs: funcURL('kbs'),
  girl: funcURL('girl14'),
  rabbitCat: funcURL('rabbitCat'),
  rabbit: funcURL('rabbit1'),
  laptop1: funcURL('1281'),
  laptop2: funcURL('1282'),
  laptop3: funcURL('1283'),
  laptop4: funcURL('1284'),
  laptop5: funcURL('1285'),
  laptop6: funcURL('1286'),
  laptop7: funcURL('1287'),
  laptop8: funcURL('1286'),
  laptop9: funcURL('1289'),
  laptop10: funcURL('9'),
  satergoPreview: funcURL('satergoPreview'),
  satergoIcon: funcURL('лого 1'),
  tShort: funcURL('лого 3'),
  branding: funcURL('лого 2'),
  ergonodesIcon: funcURL('ergonodesdesc'),
  ergonodesPreview: funcURL('ergonodespreview'),
  alineCold: funcURL('alineCold'),
  alineFont: funcURL('alineFont'),
  detail: funcURL('alineGroup'),
  aline1: funcURL('aline1'),
  aline2: funcURL('aline2'),
  aline3: funcURL('aline3'),
  samurai1: funcURL('samurai1'),
  samurai2: funcURL('samurai2'),
  samurai3: funcURL('samurai3'),
  samurai4: funcURL('samurai4'),
  samurai5: funcURL('samurai5'),
  hideEmporas: funcURL('emporasPreview'),
  emporas1: funcURL('emporas1'),
  emporas2: funcURL('emporas2'),
  emporas3: funcURL('emporas3'),
  slGooseart1: funcURL('gooseart1'),
  slGooseart2: funcURL('gooseart2'),
  slGooseart3: funcURL('gooseart3'),
  slGooseart4: funcURL('gooseart4'),
  slGooseart5: funcURL('gooseart5'),
  kbs1: funcURL('kbs1'),
  kbs2: funcURL('kbs2'),
  kbs3: funcURL('kbs3'),
  girl1: funcURL('girl1'),
  girl2: funcURL('girl2'),
  girl3: funcURL('girl3'),
  girl4: funcURL('girl4'),
  girl5: funcURL('girl5'),
  girl6: funcURL('girl6'),
  girl7: funcURL('girl7'),
  girl8: funcURL('girl8'),
  girl9: funcURL('girl9'),
  girl10: funcURL('girl10'),
  girl11: funcURL('girl11'),
  girl12: funcURL('girl12'),
  girl13: funcURL('girl13'),

}